#!/bin/sh

# This file runs whenever a DM (Desktop Manager) logs you into a graphical session.
# This file is also sourced in startx/xinit

setbg & # Run the "set background" script in the background

# xrandr --scale 2x2   # shrinks it in half
# xrandr --dpi 96      # DPI for 1080p monitors
# xrandr --output XXXX # select a monitor by cable

xrandr --dpi 192 --output HDMI-0 --rotate left --left-of DP-0  

# xrdb is the x server resource database
# This line lets you use Xresources colors/settings on startup
xrdb ${XDG_CONFIG_HOME:-$HOME/.config}/x11/xresources & xrdbpid=$!

# run the remaps script in the background
# which switches caps/esc and more
remaps &

# xcompmgr is a composite manager and helps rendering
# mpd is the music player
# dunst is for notifications
# unclutter hides my cursor when I'm not using it
# pipewire is a server for handling video/audio streams
autostart="mpd xcompmgr dunst unclutter pipewire"

for program in $autostart; do
	pidof -s "$program" || setsid -f "$program"
done >/dev/null 2>&1

# Ensure that xrdb has finished running before moving on to start the WM/DE.
[ -n "$xrdbpid" ] && wait "$xrdbpid"
